### ISSUE TITLE
Failed to init cuda while cuda is availabe

### ISSUE THREAD

**Issue by Mr-Milk** [HMS-IDAC/UnMicst#10]
I got the following errors

```
Command executed:

  python /app/unmicstWrapper.py --stackOutput --outputPath .  29.ome.tiff --channel 9 --scalingFactor 1.54

Command exit status:
  0

Command output:

  WARNING! USING unmicst-solo AS DEFAULT. THIS MODEL HAS BEEN TRAINED ON MORE TISSUE TYPES. IF YOU WANT THE LEGACY MODEL, USE --tool unmicst-legacy

  python /app/UnMicst1-5.py  29.ome.tiff --channel 8 --outputPath . --mean -1 --std -1 --scalingFactor 1.54 --GPU -1 --outlier -1 --stackOutput

Command error:
  sh: 1: nvidia-smi: not found
  2022-02-11 07:37:55.854358: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (-1)
  Killed
```

But when I run `nvidia-smi`

```
❯ nvidia-smi
Fri Feb 11 15:42:32 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 511.65       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:65:00.0  On |                  N/A |
| 34%   29C    P5    19W / 250W |   4227MiB /  8192MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I'm running on WSL2.

**Comment by clarenceyapp** [comment]
Hi @Mr-Milk 
I think what might be happening is that your CUDA version is too new. This [link](https://www.tensorflow.org/install/source#gpu) seems to state that only up to CUDA 11.2 is supported and that's if using Tensorflow 2.7.0. Unfortunately, the UnMICST container is only running Tensorflow 2.1.0, so only CUDA 10.1 is compatible in this case. Downgrading CUDA drivers on your machine is possible and might be the fastest temporary solution, but we can also try upgrading the Tensorflow version in the container to see if that doesn't break anything.

Clarence

**Comment by Mr-Milk** [comment]
Yeah, I'm using it via mcmicro, I tried exposing docker with GPU and it worked! Thanks! I think adding a section to mcmicro about GPU configuration maybe helpful?

**Comment by ArtemSokolov** [comment]
Yep, I just merged a PR that addresses this. Should be good to pull the new version with:

```
nextflow pull labsyspharm/mcmicro
```

followed by

```
nextflow run labsyspharm/mcmicro --in exemplar-001 -profile standard,GPU
```
if using Docker or
```
nextflow run labsyspharm/mcmicro --in exemplar-001 -profile singularity,GPU
```
if using Singularity

**Comment by Mr-Milk** [comment]
Sorry to reopen the issue, but the GPU selection script that uses regex to catch the output of `nvidia-smi` seems to fail in certain situations. There is an official wrapper `pynvml` that should help with this issue. I would like to open a PR to refactor the code in `GPUselect.py` if that's ok.

Example:
Input:
```  +-----------------------------------------------------------------------------+
  | NVIDIA-SMI 510.47.03    Driver Version: 511.65       CUDA Version: 11.6     |
  |-------------------------------+----------------------+----------------------+
  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
  |                               |                      |               MIG M. |
  |===============================+======================+======================|
  |   0  NVIDIA GeForce ...  On   | 00000000:65:00.0  On |                  N/A |
  | 34%   30C    P8    19W / 250W |   1197MiB /  8192MiB |     11%      Default |
  |                               |                      |                  N/A |
  +-------------------------------+----------------------+----------------------+

  +-----------------------------------------------------------------------------+
  | Processes:                                                                  |
  |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
  |        ID   ID                                                   Usage      |
  |=============================================================================|
  |  No running processes found                                                 |
  +-----------------------------------------------------------------------------+
```

Error:
```
 Traceback (most recent call last):
    File "/app/UnMicst1-5.py", line 742, in <module>
      GPU = GPUselect.pick_gpu_lowest_memory()
    File "/app/toolbox/GPUselect.py", line 19, in pick_gpu_lowest_memory
      return np.argsort(result)[0]
  IndexError: index 0 is out of bounds for axis 0 with size 0
```
